### PR TITLE
17 add login to xcode

### PR DESCRIPTION
**Pull request by OddJerbb**
Register and Login button functionalities still need to be implemented.

### CODE REVIEW

**Review by KellyPSun — COMMENTED** [review]
Seems good to me but I'm gonna have Alekhya review and approve it too before you merge since she knows more about frontend

**Comment by alekhyaku** [comment]
> I'll look at it closer when I get to the lab. Using @IBOutlet and @IBaction for these screens should? be ok since you didn't make a segue on the storyboard.  I'm just concerned with these outlets breaking in the future by accident.

**Comment by OddJerbb** [comment]
Conversion from storyboard to code is done 👍

**Comment by alekhyaku** [comment]
Looks good thanks for changing that!

**Review by alekhyaku — APPROVED** [review]

**Pull request merged**
